### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by operi-ug** [postalsys/imapflow#101]
**Describe the bug**
According to the documentation, the `socketTimeout` property in the ImapFlow client is meant to define `how many milliseconds of inactivity to allow`. 

I was expecting this to be a safety net in case the server stopped responding or something similar. But taking a closer look into the code, looks like the `socketTimeout` is defining the max amount of milliseconds the socket can exist, so if my client is in the middle of a query but the `socketTimeout` period is reached (because I created the ImapFlow client 5 minutes before this moment), I will get a `Socket Timeout` error.

**Expected behavior**
Given the documentation wording, I would expect the timeout to be cleared (`clearTimeout(this.socket)`) each time there's any kind of interaction with the server. And set again (`this.socket.setTimeout(timeout)`) every time the server has finished returning a response for any interaction.

Otherwise, we could update the documentation to make it clear that this timeout is the max amount of time the client can exist.

Please let me know if there's anything I've missed regarding how this works. And thanks for the amazing library 😅

**Comment by andris9** [comment]
ImapFlow uses the `socket.setTimeout` method provided by Node.js. You can read about how exactly works from [here](https://nodejs.org/dist/latest-v18.x/docs/api/net.html#socketsettimeouttimeout-callback)
