### ISSUE TITLE
ClosedAfterConnectTLS

### ISSUE THREAD

**Issue by takefy-dev** [postalsys/imapflow#102]
**Describe the bug**
I don't know why but i have around 500 gmail connections on 1 single ip and sometime it does this 

Error: Unexpected close
    at ImapFlow.close (/root/pluton-api-v2/node_modules/imapflow/lib/imap-flow.js:1344:23)
    at Immediate.<anonymous> (/root/pluton-api-v2/node_modules/imapflow/lib/imap-flow.js:1244:45)
    at process.processImmediate (node:internal/timers:471:21) {
  code: 'ClosedAfterConnectTLS'
}

the thing is it stop monitoring the emails of 1 gmail account until I restart the probram I tried to do a workaround with this issue to close the connection and open new connection when the error occured !

**Screenshots**
![image](https://user-images.githubusercontent.com/79745753/209940808-ab81445d-0da7-4936-a580-9eb70891c89c.png)

**Desktop (please complete the following information):**
 - OS: [Debian 10]

**Additional context**
I monitor gmail every 1100 ms

**Comment by andris9** [comment]
Nothing to do on the ImapFlow side. Unexpected connection terminations, for various reasons, are normal, and you should handle these by creating a new connection when an existing one is lost. If you do not manage connections yourself, you could use [EmailEngine](https://emailengine.app/) instead.

**Comment by takefy-dev** [comment]
> Nothing to do on the ImapFlow side. Unexpected connection terminations, for various reasons, are normal, and you should handle these by creating a new connection when an existing one is lost. If you do not manage connections yourself, you could use [EmailEngine](https://emailengine.app/) instead.

what i use to maitain connection i use the error event and then close and connect the connection is that the good way to do it ?

**Comment by DiegoFawr** [comment]
Hi. I want to know the solution, because I am having the same problem.
