### ISSUE TITLE
Integration to Office365

### ISSUE THREAD

**Issue by pit999** [postalsys/imapflow#104]
**Is your feature request related to a problem? Please describe.**
I tried to connect via Imap flow to an office 365 app for imap and it does not work. I can connect via powershell and imap-node.

**Describe the solution you'd like**
Add support for oauth2 authentication.

**Describe alternatives you've considered**

**Additional context**
add Imap option like       xoauth2: base64Encoded,

This code work as token for office 365 app with imap-node:

const base64Encoded = await getToken(mailId, tokenRequest);

const msalConfig = {
  auth: {
    clientId: "client Id",
    authority: "https://login.microsoftonline.com/tenant Id/",
    clientSecret: "clientsecret",
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel: any, message: any, containsPii: any) {
        console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: msal.LogLevel.Verbose,
    }
  }
};

const tokenRequest = {
  scopes: ["https://outlook.office365.com/.default"],
};

/**
 * Acquires token with client credentials.
 * @param {object} tokenRequest 
 */
async function getToken(mailId: string, tokenRequest: any) {
  const cca = new msal.ConfidentialClientApplication(msalConfig);
  const msalTokenCache = cca.getTokenCache();
  let authResponse = await cca.acquireTokenByClientCredential(tokenRequest);
  return Buffer.from([`user=${mailId}`, `auth=Bearer ${authResponse.accessToken}`, '', ''].join('\x01'), 'utf-8').toString('base64');
}

**Comment by andris9** [comment]
ImapFlow is the lower-level IMAP handler for [EmailEngine](https://emailengine.app/), and EmailEngine already manages all token renewals. There are no plans to duplicate features from EmailEngine to ImapFlow. If you are not using EmailEngine, then you need to provide the tokens to ImapFlow yourself. If you are using EmailEngine, you can read about setting up OAuth2 support for Outlook with it [here](https://docs.emailengine.app/setting-up-oauth2-with-outlook/)

**Comment by pit999** [comment]
I created the token by myself (as explained in my comment above), but it does not work with imap-flow (it does with imap-node).
But don't worry - I will use imap-node, everything I need is covered with this library.
