### ISSUE TITLE
SearchObject `or` gives inconsistent results

### ISSUE THREAD

**Issue by davellx** [postalsys/imapflow#106]
Hello,

I was trying to make a fetch request with a bunch of `or` but the results were not what I expected.

the request looks like that : 
```
{or: [
  { to: 'myemail@domain.com', from: '@anotherdomain.com' },
  { to: 'myemail@domain.com', from: '@aseconddomain.com' },
  { to: 'myemail@domain.com', from: '@athirddomain.fr' },
  { to: 'anotheremail@domain.com', from: '@anotherdomain.fr' },
  { to: 'anotheremail@domain.com', from: '@aseconddomain.com' }
]
}
```

and the request obtained is : 
`9 UID SEARCH OR OR OR TO myemail@domain.com FROM @anotherdomain.com TO myemail@domain.com FROM @aseconddomain.com OR TO myemail@domain.com FROM @athirddomain.fr TO anotheremail@domain.com FROM @anotherdomain.fr TO anotheremail@domain.com FROM @aseconddomain.com`

I'm not IMAP Search Langage fluent enought to verify if the syntax is correct but there was no results from the query even if some emails should have been listed.

So I tried to add parenthesis around each element by modifying the walkOrTree function of the search compiler.

```
let walkOrTree = entry => {
	if (Array.isArray(entry)) {
		if (entry.length > 1) {
			attributes.push({ type: 'ATOM', value: 'OR' });
		}
		entry.forEach(el => {
			attributes.push({ type: 'TEXT', value: '(' });
			walkOrTree(el)
			attributes.push({ type: 'TEXT', value: ')' });
		}
		return;
	}
	if (entry && typeof entry === 'object') {
		walk(entry);
	}
};

```
And it worked, the request returned the emails I expected, and the debug log is more readable. I know it adds a little overhead to the request but if it's for better results it may be not so important. :)

**Comment by davellx** [comment]
The RFC 3501 seems to tell the other way : 
```
When multiple keys are specified, the result is the intersection
      (AND function) of all the messages that match those keys.  For
      example, the criteria DELETED FROM "SMITH" SINCE 1-Feb-1994 refers
      to all deleted messages from Smith that were placed in the mailbox
      since February 1, 1994.  **A search key can also be a parenthesized
      list of one or more search keys (e.g., for use with the OR and NOT
      keys).**
```
But it's your project, you do what you want/need. :)
Thanks for the answer.

**Comment by wilker7ribeiro** [comment]
Any chance of this being fixed?

I will probably have to use another tool as this is critical for my use case, and there is no workaround for it.
