### ISSUE TITLE
messageFlagsAdd deadlocks/freezes if fetch is used

### ISSUE THREAD

**Issue by PRR24** [postalsys/imapflow#110]
**Describe the bug**
messageFlagsAdd does not return if fetch was used on the client earlier

**To Reproduce**
```ts
await client.connect();
let lock = await client.getMailboxLock("INBOX");
try {
    let processed: number[] = [];
    for await (let msg of client.fetch({ seen: false }, { source: { maxLength: 2 * 1024 * 1024 } })) {
        console.log(msg.seq);
        processed.push(msg.seq);
    }
    if (processed.length) {
        await client.messageFlagsAdd(processed, ["\\Seen"]); // Freezes without any error/log
    }
// ...
```
If I take the seq logged to the console and use the solution without fetch:
```ts
await client.connect();
let lock = await client.getMailboxLock("INBOX");
try {
    let processed: number[] = [4517];
    if (processed.length) {
        await client.messageFlagsAdd(processed, ["\\Seen"]); // Works perfectly
    }
```
everything works as expected.

Ubuntu 22.04, imapflow 1.0.119

**Comment by PRR24** [comment]
Made a mistake while oversimplifying the repro case.
The problem occurs when fetch() is not fully processed, eg either with:
```ts
await client.connect();
let lock = await client.getMailboxLock("INBOX");
try {
    let processed: number[] = [];
    for await (let msg of client.fetch({ seen: false }, { source: { maxLength: 2 * 1024 * 1024 } })) {
        console.log(msg.seq);
        processed.push(msg.seq);
        break; // Important for repro
    }
    if (processed.length) {
        await client.messageFlagsAdd(processed, ["\\Seen"]); // Freezes without any error/log
    }
// ...
```
Or with (the original code I started to track the problem down from):
```ts
await client.connect();
let lock = await client.getMailboxLock("INBOX");
try {
    for await (let msg of client.fetch({ seen: false }, { source: { maxLength: 2 * 1024 * 1024 } })) {
        console.log(msg.seq);
        client.messageFlagsAdd({ seq: msg.seq }, ["\\Seen"]); // Freezes without any error/log
    }
// ...
```
Just for future record, what is the recommended way to safely cancel the fetch loop?

**Comment by andris9** [comment]
Oh, I guess I haven't documented it well enough (if at all 🤔). You can not run any IMAP command before the previous one has finished. So you can't run `messageFlagsAdd` inside the `fetch` loop. This is because you can only process a single IMAP command at a time (can't do anything in parallel in the same session), and the fetch command has not finished yet. For other commands, it's not a big issue, as ImapFlow just pipelines these commands, but the fetch loop is special – it allows you to run your code while the command is still being executed.

**Comment by dotsinspace** [comment]
> Oh, I guess I haven't documented it well enough (if at all 🤔). You can not run any IMAP command before the previous one has finished. So you can't run `messageFlagsAdd` inside the `fetch` loop. This is because you can only process a single IMAP command at a time (can't do anything in parallel in the same session), and the fetch command has not finished yet. For other commands, it's not a big issue, as ImapFlow just pipelines these commands, but the fetch loop is special – it allows you to run your code while the command is still being executed.

is there any way to mark message seen while reading its information. even example on npm is confusing because as per your statement i can only work with 1 email at any given time. ( Like fetching unseen then marking it seen )
