### ISSUE TITLE
client.on('exists',function()) will miss some email

### ISSUE THREAD

**Issue by youxiaohou** [postalsys/imapflow#112]
**Describe the bug**
I use the client.on('exists', function()) to get the latest email , sometimes imapflow will miss some emails ,the result are **imapflow** vs **emailjs-imap-client**

Picture below: 498 is missing in imapflow, but emailjs-imap-client is ok

**Screenshots**
![image](https://user-images.githubusercontent.com/82362675/219038093-b177ed4f-b850-438a-a3ef-48eff00b0940.png)

**Desktop (please complete the following information):**
Windows 11 x64

**Additional context**
My code below 
```js
const client = new ImapFlow(confOption);
const main = async () => {
    await client.connect();

    let lock = await client.getMailboxLock('INBOX');
    try {
        let latestID = +client.mailbox.exists;
        let messages = client.fetch(`${latestID - 2}:${latestID}`, {source: true, uid: true, envelope: true, flags: true});
        console.log(base.yellow('========== Getting History Email!!! =========='));
        for await (let msg of messages) {
            await config.printEmail(msg)
        }

        console.log(base.yellow('========== Listening Latest Email ... =========='));
        client.on('exists', async data => {
            let msg = await client.fetchOne(data.count, {source: true, uid: true, envelope: true, flags: true});
            await config.printEmail(msg)
        });

        client.on('error', err => {
            console.log(`error：${err.message}`);
        });

    } finally {
        // Make sure lock is released, otherwise next `getMailboxLock()` never returns
        lock.release();
    }

    // log out and close connection
    //await client.logout();
};

main().catch(err => console.error(err));
```

**Comment by andris9** [comment]
IMAP can be tricky. 'exists' event only triggers if you are listening to it exactly at the time when the event is sent by the server. If you are, for example, still looping through the `client.fetch` results, then 'exists' does not trigger. So, set the handler _before_ running any other commands to make sure that the listener is set when those events happen.

ImapFlow is built to power [EmailEngine](https://emailengine.app/). You can compare your code against EmailEngine by installing a free trial of EmailEngine and checking if EmailEngine detects those new emails or not (EmailEngine sends a webhook for every new email). If EmailEngine detects all emails and your code does not, then something is wrong with your code as EmailEngine also uses ImapFlow for all IMAP commands.

**Comment by cesaryuan** [comment]
Hi @youxiaohou, could you tell me what solution you finally adopted to implement email monitoring? Thanks!
