### ISSUE TITLE
Typescript typings stuck at v1.0.11

### ISSUE THREAD

**Issue by Indeedornot** [postalsys/imapflow#113]
Hi!
I've been using this package in my personal project, however when I've tried to use `downloadMany` I've noticed that it's not defined on ImapFlow class due to typings not being updated.

Would there be a possibility for them to be updated?

**Comment by andris9** [comment]
ImapFlow does not have official support for typings. These built-in typings were originally autogenerated from the JSDoc comments but contained too many conflicts with the actual code base and were unusable. The Definitely Typed typings are unofficial. I don't know in which state these are.
