### ISSUE TITLE
German Umlauts not shown

### ISSUE THREAD

**Issue by Flo0806** [postalsys/imapflow#114]
**Describe the bug**
The subject object does not show german umlauts like ä ü ö.

**To Reproduce**
You can use the sample code only be sure that the email you fetch has umlauts inside its subject.
```
const { ImapFlow } = require('imapflow');
const client = new ImapFlow({
    host: 'ethereal.email',
    port: 993,
    secure: true,
    auth: {
        user: 'garland.mcclure71@ethereal.email',
        pass: 'mW6e4wWWnEd3H4hT5B'
    }
});

const main = async () => {
    // Wait until client connects and authorizes
    await client.connect();

    // Select and lock a mailbox. Throws if mailbox does not exist
    let lock = await client.getMailboxLock('INBOX');
    try {
        // fetch latest message source
        // client.mailbox includes information about currently selected mailbox
        // "exists" value is also the largest sequence number available in the mailbox
        let message = await client.fetchOne(client.mailbox.exists, { source: true });
        console.log(message.source.toString());

        // list subjects for all messages
        // uid value is always included in FETCH response, envelope strings are in unicode.
        for await (let message of client.fetch('1:*', { envelope: true })) {
            console.log(`${message.uid}: ${message.envelope.subject}`);
        }
    } finally {
        // Make sure lock is released, otherwise next `getMailboxLock()` never returns
        lock.release();
    }

    // log out and close connection
    await client.logout();
};

main().catch(err => console.error(err));
```

**Expected behavior**
The "clean" subject is: `GMX Täßt` This is what I expect to get. This is decoded subject from the ImapFlow lib: `=?UTF-8?Q?GMX_T=C3=A4=C3=9Ft?=` and this I get from the `message.source.toString()`: `GMX T├ñ├ƒt` (Should be: GMX Täßt)

**Desktop (please complete the following information):**
 - Windows & Mac
 - NodeJS 19

**Comment by andris9** [comment]
ImapFlow is only an IMAP client, and it does not handle MIME encodings. ImapFlow provides you with strings as they are encoded by the server. You are supposed to handle encoding on the client side.

If you want to get Unicode string values, then you can use a higher-level solution like [EmailEngine](https://emailengine.app/). EmailEngine uses ImapFlow under the hood for IMAP and, amongst other things, adds the compatibility layer that manages everything encoding-related.

**Comment by andris9** [comment]
Now that I re-checked, it seems I forgot that ImapFlow actually does some encoding handling. If you get `GMX T├ñ├ƒt` then you are doing some kind of double-decoding somewhere.

**Comment by Flo0806** [comment]
Hello,
This part: 
```
 for await (let message of client.fetch('1:*', { envelope: true })) {
            console.log(`${message.uid}: ${message.envelope.subject}`);
        }
```
shows the wrong `GMX T├ñ├ƒt`. At this time no other encoding running from my side.

**Comment by andris9** [comment]
Can you provide the original email source? Are you sure you are not sending it invalidly so that it ends up in the wrong format on the email server? Because ImapFlow obviously supports all Unicode symbols, including emojis, umlauts, Asian characters, and so on.

**Comment by Flo0806** [comment]
It's a GMX and a All-Inkl.com IMAP server... But: Youre right... It's the shell. I have now wrote the subjects into a simple text file and all looks great! It's not a problem with your lib!

And - it's not your part - but do you know how to solve the problem with the shell (PowerShell and command promt)?

**Comment by andris9** [comment]
I don't use Windows myself, so I don't know the solution 🤷‍♂️
