### ISSUE TITLE
Event listener for new email

### ISSUE THREAD

**Issue by QiYuan08** [postalsys/imapflow#116]
Hi is there any listener for new emails received in the mailbox? I couldn't find on in the documentation

**Comment by andris9** [comment]
IMAP servers emit the EXISTS event that you can use with https://imapflow.com/module-imapflow-ImapFlow.html#event:exists

Be aware though that this does not give you the new email but notifies you that the message count has been changed, so you need to find the actual new email yourself. It is also only valid for the currently opened mailbox folder. If the folder is not open, then you never receive that event.

If you want a more convenient notification about new messages, use [EmailEngine](https://emailengine.app) as it sends webhooks for all new emails in every mailbox folder and includes all the details of the new emails.

**Comment by jondycz** [comment]
I apologize if this reopens the issue, but I followed the documentation which suggested using locks instead. Does the library not emit the exists event when I destroy the lock? Also, it seems like the event is delayed by 5 minutes. I guess that depends on the server implementation. Either way, what is the recommended way, in case mailbox locks do not support this?

**Comment by andris9** [comment]
@jondycz email servers only send update notifications for messages in the currently selected folder. So, if no folder is selected, you don’t get a notification. If you have another folder selected than the one where the change happens - you do not get a notification. If you select the folder _after_ the change - you do not get a notification.

**Comment by jondycz** [comment]
Yes, I do know that. I am asking if doing:
```
let lock = await client.getMailboxLock('INBOX');
//Some email fetching
lock.release();
```
Closes the inbox, or keeps it open, just prevents a function from being called in parallel by locking the inbox to a single process.

I am also confused about the usage of client.mailboxSubscribe(); as that doesn't seem to do anything different than client.mailBoxOpen(); From the name I would have guessed that Subscription would listen for the exists event, while others would close the connection but that is not the case.

So in order for the event to fire, I need to use client.mailBoxOpen() within an onload event and on close event as to keep the mailbox open at all times?

```
async function doStuff(imap){
//My code to do something with mails
}
client.on('ready', async () => {
  await imap.connect();
  imap.mailboxOpen('INBOX');
  doStuff(imap);
});
imap.on('close', async () => {
  await imap.connect();
  imap.mailboxOpen('INBOX');
  doStuff(imap);
});

imap.on('exists', async (data) => {
    doStuff(imap);
});
```
So if I'm not mistaken, for my use case I can't use the lock system, as releasing the lock seems to close the inbox? The code above is prone to firing multiple times if the code execution took longer than the time between on exists events (which seem to fire every 5 minutes). And the client.mailboxSubscribe(); seemed to change nothing about the code behavior.

**Comment by andris9** [comment]
`mailboxSubscribe` runs the SUBSCRIBE command defined [here](https://datatracker.ietf.org/doc/html/rfc3501#section-6.3.6). Both `mailboxOpen` and `getMailboxLock` run the SELECT command defined [here](https://datatracker.ietf.org/doc/html/rfc3501#section-6.3.1), the difference being that you can't run another `getMailboxLock` until the lock from the previous one has been released. You receive notifications like `exists` for the currently SELECT'ed folder. So, if nothing is SELECT'ed, you do not get notifications. If you SELECT another folder, you start receiving notifications for the newly selected folder but stop receiving notifications for the previously selected folder. You can only select a single folder at a time.

If you need notifications for all folders, irrelevant if being currently selected or not, you would either build the logic on top of these primitives yourself, or use [EmailEngine](https://emailengine.app/) that is not free (ImapFlow is the IMAP library built specifically for EmailEngine, but unlike EmailEngine, I released ImapFlow under open source license).

Also, ImapFlow is only good for a single session. Once the connection is closed, you can't use that ImapFlow object anymore and would have to create a new ImapFLow object. IMAP is a stateful protocol and if you use the previous session info, it will get into conflict with the new session.

**Comment by andris9** [comment]
Yes, create a new ImapFlow object when connecting. Lock release does not deselect. Instead, it allows you to use `getMailboxLock` again. The reasoning behind the locking system is that IMAP commands are not folder specific. The lock ensures that the folder you expect to be currently open really is. Otherwise you might be running your commands against a different folder.
