### ISSUE TITLE
doc bug, fetchOne(), example

### ISSUE THREAD

**Issue by stheine** [postalsys/imapflow#118]
**Describe the bug**

you document
```
// fetch UID for all messages in a mailbox
let lastMsg = await client.fetchOne('*', {uid: true})
```

but this seems to be a c&p issue and should rather read
```
// fetch UID for the newest message in a mailbox
```

**To Reproduce**
https://imapflow.com/module-imapflow-ImapFlow.html#fetchOne-examples

**Comment by andris9** [comment]
Thanks. It's a copy-pasta issue. Fixed with 52d72beafef3151e8b3620e732eff66b6fc9706d
