### ISSUE TITLE
doc bug, downloadMany(), example

### ISSUE THREAD

**Issue by stheine** [postalsys/imapflow#119]
**Describe the bug**

you document

```
// download body part nr '1.2' from latest message
let response = await client.downloadMany('*', ['2', '3]);
```

but this seems to be a c&p issue and should rather read

```
// download the body parts 2 & 3 of the newest message
```

**To Reproduce**
https://imapflow.com/module-imapflow-ImapFlow.html#downloadMany-examples

**Comment by andris9** [comment]
Thanks. It's a copy-pasta issue. Fixed with 52d72beafef3151e8b3620e732eff66b6fc9706d
