### ISSUE TITLE
Calling .list() freezes email count for all inboxes

### ISSUE THREAD

**Issue by x6pnda** [postalsys/imapflow#124]
**Describe the bug**
Calling .list() on the client freezes the email count for inboxes. Even if an new email arrive and you request those with the mailboxlock, the count stays the same. Removing it updates the emails as expected

**To Reproduce**
```
async function test() {
    const client = new ImapFlow({
        host: 'imap.gmail.com',
        port: 993,
        secure: true,
        auth: {
            user: '', 
            pass: '', 
        },
    });
    await client.connect();
    setInterval(async () => {
        let lock;
        try {
            // NOTE: Toggle this line below. Disabled = showing updated count. Enabled = count stays the same even if an new email arrives
            const boxes = await client.list();
            lock = await client.getMailboxLock('INBOX');
            console.log(client.mailbox.exists);
        } catch (err) {
            console.error(err);
        } finally {
            lock?.release();
        }
    }, 1000 * 5);
}
```

**Expected behavior**
That the count updates. With it disabled, it shows correctly the latest count if a new email has arrived. With it enabled is stays on the same number as the first time it pulled emails.

**Comment by andris9** [comment]
ImapFlow returns whatever the server provides to it
