### ISSUE TITLE
Error: getaddrinfo ENOTFOUND imap.gmail.com

### ISSUE THREAD

**Issue by DimaDyachenko** [postalsys/imapflow#126]
Sometimes I've got `Error: getaddrinfo ENOTFOUND imap.gmail.cm`. It could be resolved after computer reboot. What it could be?

**Comment by andris9** [comment]
`imap.gmail.cm` seems to be a wrong hostname. Use `imap.gmail.com` instead.

**Comment by DimaDyachenko** [comment]
sorry, there was `imap.gmail.com`, but anyway it works only after reboot

**Comment by vhscom** [comment]
Saw the same problem today. Resolved by running `nslookup imap.gmail.com`.

**Comment by vhscom** [comment]
Saw this error today. Resolved by running `nslookup imap.gmail.com`.

**Comment by vhscom** [comment]
Saw this error today. Resolved by running `nslookup imap.gmail.com` on host machine.

**Comment by vhscom** [comment]
Saw the same error today. Resolved by running `nslookup imap.gmail.com`.
