### ISSUE TITLE
I don't get message from an email.

### ISSUE THREAD

**Issue by Illia-S-dev** [postalsys/imapflow#140]
**Describe the bug**

**To Reproduce**
1. Open My project;
2. Run cypress test;
3. Wait the ending pf the test;
4. See an error

**Expected behavior**
I get code from an email message for my test. Today around at 12:00 everything was worked well.

**Screenshots**
![Screenshot 2023-09-05 at 09 12 51](https://github.com/postalsys/imapflow/assets/66375193/923d66c1-ce69-4db6-b7ba-7603334c2c5c)
![Screenshot 2023-09-05 at 09 13 14](https://github.com/postalsys/imapflow/assets/66375193/840475d7-c6f0-41d9-b891-1cf7b41ad452)

**Additional context**
Yesterday and today I don't get message from an email. As you can see at the screens connection is closed.

I use the following libraries:
- "imapflow": "^1.0.143",
- "@types/nodemailer": "^6.4.9",
- "nodemailer": "^6.9.4",

The code which I use:
<img width="839" alt="Screenshot 2023-09-05 at 09 36 10" src="https://github.com/postalsys/imapflow/assets/66375193/d1f7d1c2-6370-4544-9f0f-d3f0d1f8104d">

Could you help me, please?

**Comment by andris9** [comment]
Due to rampant abuse, I had to disable inbound emails for Ethereal.email accounts (botnets were using these accounts). Now, you can only use Ethereal.email for authenticated SMTP emails when sending to ports 465 or 587, but not for MX on port 25.
