### ISSUE TITLE
UNKEYWORD search not working (on gmail)

### ISSUE THREAD

**Issue by tobschaber** [postalsys/imapflow#144]
**Describe the bug**
I am performing a search to a gmail account with the following query:

```

(connect etc..)
await this.client.mailboxOpen('INBOX');
await this.client.search(
                {
                    unKeyword: 'processed'
                }, {uid: true});

```

The inbox contains 13 mails, and non of them has the "processed" flag set. Thus I would expect 13 mails as search result. Instead I get zero.
I tried different ways of setting the flag but all lead to the same result.

`await this.client.messageFlagsAdd({uid: uid}, ['processed'], {uid: true});`

version: imapflow/1.0.144

As I tried so many things and nothing worked to get the search correctly, maybe you have any hint for me?

Thank you and kind regards

**Comment by tobschaber** [comment]
As this also might be a gmail specific issue, I found the following solution which seems to work in the source code (not in the documentation) for the query:

gmraw: '!label:processed'

**Comment by andris9** [comment]
The server decides how to respond to a search query, and there is not much ImapFlow as a client can do about it. For Gmail servers, you can use the non-standard gmRaw property.
