### ISSUE TITLE
Hang on messageMove, returns false after long time

### ISSUE THREAD

**Issue by stratbasher** [postalsys/imapflow#147]
**Describe the bug**
When trying to use messageMove with a uid, the code pauses for a long time before finally returning false and not moving the message.

I can confirm that it does grab all the emails and the pertinent info for the email. If I remove the messageMove command, the code runs through all the emails in that folder. Also the environment variable is loading properly from process.env.x entries (IMAP_MAILBOX, IMAP_PROCESSED_MAILBOX, etc).

**To Reproduce**
My email account is Outlook.com.

**Example Code**
```
const main = async () => {
    // Connect
    await mailClient.connect();

    let lock = await mailClient.getMailboxLock(process.env.IMAP_MAILBOX);

    let count = 0;
    for await (let msg of mailClient.fetch('1:*', { uid: true, source: true })) {
        count++;
        console.log(`Processing email ${count}`)
        const mail = await(simpleParser(msg.source.toString()));
        const mailFrom = mail.from.value[0].address;

        let result = await mailClient.messageMove(msg.uid, process.env.IMAP_PROCESSED_MAILBOX, {uid: true});
        console.log(result);
        }
    }
}
```

Code hangs at the "let result = await mailClient.messageMove" line

Eventual error code caught is "Connection not available". This does not have a "response" so that fails as well

```
'Error: Connection not available
    at ImapFlow.close (C:\Users\<redacted>\node_modules\imapflow\lib\imap-flow.js:1443:36)
    at TLSSocket._socketTimeout (C:\Users\<redacted>\node_modules\imapflow\lib\imap-flow.js:646:26)
    at TLSSocket.emit (node:events:512:28)
    at Socket._onTimeout (node:net:564:8)
    at listOnTimeout (node:internal/timers:568:17)
    at process.processTimers (node:internal/timers:511:7)'
```
![image](https://github.com/postalsys/imapflow/assets/4118916/36fea6ab-1ef3-4bac-859e-ea905dd65d16)

**Expected behavior**
messageMove would move the message to the specified folder path (tested with Trash as well, no dice) and return true

**Screenshots**
Code and screenshots above

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Environment: Node.js
 - Version: 19.7

**Comment by andris9** [comment]
You can not run any IMAP commands in the fetch for loop. You have to wait until the for loop has completed.
