### ISSUE TITLE
GREEETING_TIMEOUT error is thrown when i try to connect from a hosted server

### ISSUE THREAD

**Issue by ejerenwaavis** [postalsys/imapflow#148]
**Describe the bug**
Whenever i try to read a mialbox from my hosted web application the GREEETING_TIMEOUT error is thrown, however when i run the same exact application from my local machin (localhost), it works just fine.

**To Reproduce**
1. Host NodeJS Web Application on Namecheap
2. make a call to API endpoint that should begin reading inbox
3. Error is thrown

**Expected behavior**
Whenever a call is made to the API when hosted on a local machine, it should return a JSON object which has a summary of what data was read and if the reading was successfull or not. see screenshots

 Expected Behavior:
 ![image](https://github.com/postalsys/imapflow/assets/59552917/452969b4-b2c2-4a4a-9016-8b3edb4d5b77)

Buggy Behavior:
![image](https://github.com/postalsys/imapflow/assets/59552917/2f2acec8-ed07-4710-8acf-58d9192fe096)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

Thank you in advance

**Comment by andris9** [comment]
Your TLS config (`secure` option) is probably wrong. Or some other connection options are wrong.
