### ISSUE TITLE
Get mailbox name from message

### ISSUE THREAD

**Issue by aymen3009** [postalsys/imapflow#153]
hey I am using All Mailbox to search for emails 
``` ts
  await client.connect();
  const list = await client.list();
  const allMessagesBoxName = list.find((box) => box.specialUse === '\\All')?.path;
   lock = await client.getMailboxLock(allMessagesBoxName || 'INBOX'); // Acquire the mailbox lock


```

is there a way to know if the msgs found belong to which mailbox ... I want to find out if they are in the trash or not that's sufficient for me

**Comment by andris9** [comment]
Gmail has 3 folders:
* All Mail
* Trash
* Junk
All other "folders" are virtual labels in front of the All Mail folder. As such, you can not access Trash emails from the All Mail folder.
