### ISSUE TITLE
how to use a RegExp in the SearchObject?

### ISSUE THREAD

**Issue by Chiapos** [postalsys/imapflow#154]
**Is your feature request related to a problem? Please describe.**
I need to find an "exact match" of an email "subject". 
I have two emails with the "Spam subject" and "Not spam subject" subjects
I need to move an email with the "Spam subject" to a corresponding folder "spam-assasin-spam".
This is what I do using SearchObject:
`
imap().moveMessage({subject: "Spam subject"},"INBOX.sa-spam");
`
This code will match both emails. I need to select only one email with "exact match".

**Describe the solution you'd like**
Implement regex?

**Describe alternatives you've considered**
I can generate the email's subjects with a unique string. But I wonder if that's possible to use "exact match" when working with "string"?

**Additional context**
https://imapflow.com/global.html#SearchObject

**Comment by andris9** [comment]
IMAP SEARCH command is very limited and dependent on the specific server implementation.
