### ISSUE TITLE
Fetch or Download method inside a for await ( const msg of imap.fetch() ) causes an infinite waiting

### ISSUE THREAD

**Issue by gicu95** [postalsys/imapflow#159]
**Describe the bug**
Hi guys, when i use the download (or fetch) method inside a for await loop, while retrieving messages list, it never finishes. 
From the logs i can see that the message is fetched from the folder but the download method inside the for loop doesn't respond causing an infinite waiting...

**To Reproduce**
```js

const imap = new ImapFlow(connection_info);
await imap.connect();

await imap.mailboxOpen('INBOX');
    
for await  ( const msg of imap.fetch('1:*', { uid: true, flags: true, bodyStructure: true, size: true})) {
     const attachment = await imap.download(msg.uid, '1.2', { uid: true});
}

await imap.mailboxClose();
await imap.close();

```

**Expected behavior**
Retrieve the attachment content

**Version**
imapflow v1.0.136 on node version v19.6.1

**Comment by andris9** [comment]
Yes, you can not run any of the imap commands until fetch finishes, otherwise you get into a deadlock

**Comment by gicu95** [comment]
Gotcha, i'll do a workaround, thanks!

> Yes, you can not run any of the imap commands until fetch finishes, otherwise you get into a deadlock

**Comment by lucasPARISOT** [comment]
Thank you for the info.
Spend a few hours today thinking it was because of an error from my email provider.

You should add this info on the documentation / npm package page because I don't think we will be the last in this situation.

**Comment by andris9** [comment]
I added a comment about this behaviour to the `await fetch` example [here](https://imapflow.com/module-imapflow-ImapFlow.html#fetch-examples).

The primary purpose of ImapFlow is to provide IMAP connectivity for [EmailEngine](https://emailengine.app/), and as such, I haven't been very active in documenting features or edge cases that do not concern EmailEngine as EmailEngine never tries to run these operations.
