### ISSUE TITLE
Re-order Mailboxes

### ISSUE THREAD

**Issue by JackBailey** [postalsys/imapflow#160]
**Is your feature request related to a problem? Please describe.**
Yes, I'm creating a tool to apply labels dynamically based off of an addy.io alias which works great using this tool, but new labels are put at the bottom of the list, the only way around it is removing and re-adding the labels in the order I want them. 

**Describe the solution you'd like**
Provide a method to set the position of a mailbox if possible.

**Comment by andris9** [comment]
I don't see how ImapFlow could fix this, unless there is some kind of special IMAP command argument that sets the ordering. Closing for now. If you have additional information about how to set labels in a specific order, then let me know.
