### ISSUE TITLE
Add property 'id' in FetchMessageObject

### ISSUE THREAD

**Issue by b0939261761** [postalsys/imapflow#164]
Hello,
Please add the "id" property on the FetchMessageObject to the documentation.

[https://github.com/postalsys/imapflow/blob/d73a56ace802616c321ca4c45c64c7f273c64992/lib/tools.js#L351](https://github.com/postalsys/imapflow/blob/d73a56ace802616c321ca4c45c64c7f273c64992/lib/tools.js#L351)
```js

   if (map.emailId || map.uid) {
        ...
            map.id = map.emailId || createHash('md5').update([path, mailbox.uidValidity.toString(), map.uid.toString()].join(':')).digest('hex');
   }

```

Thank's

**Comment by andris9** [comment]
This "id" is semi-private, it should not be listed in the docs
