### ISSUE TITLE
Advanced OAuth2 handling

### ISSUE THREAD

**Issue by PRR24** [postalsys/imapflow#177]
Please consider adding advanced OAuth2 handling to the IMapFlow, namely:
* support for "oauth2_provision_cb" callback;
* support for "token" message and "accessUrl" setting.
* maybe more, like 2LO support

Thank you.

**Comment by benbucksch** [comment]
@andris9 This makes sense to keep OAuth2 login out of scope.

**Comment by PRR24** [comment]
To be honest, it sounds reasonable for me as well. The trigger behind the request was that for some reason, the OAuth handling was considered to be in scope for NodeMailer.
As I am using both of these great libraries, this discrepancy was weird for me and I would prefer to use the exact same approach for both cases, either delegating it to the library or using some other / my own implementation.
