### ISSUE TITLE
Make examples

### ISSUE THREAD

**Issue by TheGP** [postalsys/imapflow#179]
Add examples with getting body, etc and add comments to each line and parameters.
For example, wtf is this: client.fetch('1:*' ??

**Comment by andris9** [comment]
I would suggest googling for tutorials to understand what these commands actually do. For example, this seems like a good article https://www.atmail.com/blog/imap-commands/

**Comment by TheGP** [comment]
I don't care what they do, I need to get a body of emails, not read spend hours on BS.
