### ISSUE TITLE
Add email references in enveloppe

### ISSUE THREAD

**Issue by flogh** [postalsys/imapflow#180]
Hello,

Would it be possible to add "references" in the enveloppe of FetchMessageObject, next to "inReplyTo" ?

This would help me group emails by discussion

Thank you

**Comment by andris9** [comment]
Envelope structure is defined in [RFC5301](https://datatracker.ietf.org/doc/html/rfc3501#page-77), ImapFlow returns the data provided by the server and there is no References entry in that structure. If you need that value, request it as a Header.

**Comment by HugoGresse** [comment]
I think something like this can do it: 
```typescript
export const parseReferencesHeaders = (headers: Uint8Array) => {
    const headerString = new TextDecoder().decode(headers)
    const matches = headerString.match(/References: ((?:<[^>]+>\s*)+)/);
    const references = matches?.[1].trim().split(/\s+/) || [];

    return references
}
```
