### ISSUE TITLE
Please clarify docs

### ISSUE THREAD

**Issue by ile** [postalsys/imapflow#183]
[This](https://imapflow.com/module-imapflow-ImapFlow.html#idle) seems unclear:

>  If idle() is called manually then it does not return until IDLE is finished which means you would have to call some other command out of scope.

What does this mean: "you would have to call some other command out of scope"? When does the `idle()` return exactly?

Maybe clarify the docs?

Thanks.

**Comment by andris9** [comment]
It's an async issue.

```js
await connection.idle()
// this line is never reached because the idle never completes
```

vs

```js
setTimeout(()=>{
  connection.noop();
}, 10*1000);
await connection.idle()
// this line is reached after 10 seconds because executing another IMAP operation will terminate the pending IDLE
```

ImapFlow only exists for [EmailEngine](https://emailengine.app/), so I haven't paid too much attention to docs or examples.

**Comment by ile** [comment]
Ok, thanks. "Out of scope" was a bit confusing - it seems it's just when another IMAP operation is called during IDLE.
