### ISSUE TITLE
Maybe add options object to listTree

### ISSUE THREAD

**Issue by DrFuehrer02** [postalsys/imapflow#194]
The list function provides a options object as a parameter with some available flag (e.g. statusQuery, specialUseHints). It would be nice to have these as well on the listTree function. It would only be a slight code change. Thank you so much.

**Comment by Bombastickj** [comment]
Funny, I was just looking for a way to do this! I'd appreciate this feature too 👍

**Comment by andris9** [comment]
_Should_ be fixed in v1.0.161 (meaning that I did not actually test it, only added the optional argument and passed it to the LIST command)

**Comment by li-zao** [comment]
V：1.0.169，listTree support listOption with statusQuery, but ListTreeResponse has no StatusObject yet. really appreciate if it got fixed, otherwise have to do two requests to get folder list with unseen number.
