### ISSUE TITLE
Unexpected behavior while fetch if network error occurs

### ISSUE THREAD

**Issue by udik-chudik** [postalsys/imapflow#201]
There is an unexpected behavior during some kind of errors. This make the usage of such a beautiful lib unreliable

**To Reproduce**

The code from README: while fetching is in progress
```js
await (let message of client.fetch('1:*', { envelope: true })) 
```
and network error occurs (for example turn wifi off/on), the program crashes with
```
      throw er; // Unhandled 'error' event
```
After adding a listener for an error event, for example:
```js
client.on('error', console.log)
```
crashes stopped. But none of `.catch` are fired: `try` in 'main'  neither `main().catch`. `main().then` does not fires as well.

**Expected behavior**
Expect
```js
await (let message of client.fetch('1:*', { envelope: true })) 
```
to `throw` if a network error occurs.

**Additional context**
Node v20.14.0

**Comment by andris9** [comment]
fetch and all other commands throw on IMAP response failures - these are errors you can recover from in the same IMAP session. For network etc failures that break the IMAP session, you need to set up the generic error handler, and when it fires, destroy the existing ImapFlow object and create and connect a new one.
