### ISSUE TITLE
Posteo.de `await client.connect()` never concludes

### ISSUE THREAD

**Issue by benjaminpreiss** [postalsys/imapflow#215]
**Describe the bug**
Promise `await client.connect()` never concludes when connecting to posteo.de IMAP via port 993, TLS.

**To Reproduce**

Execute the following script (e.g. with [bun JS](https://bun.sh/) in my case):

```ts
import { ImapFlow } from "imapflow";
import { processMails } from "./mails";

export async function main() {
	const imapFlowClient = new ImapFlow({
		host: "posteo.de",
		port: 993,
		secure: true,
		auth: {
			user: "your-posteo-user-name",
			pass: "your-posteo-user-pass",
		},
		logger: {
			debug(obj) {
				console.log(obj);
			},
			error(obj) {
				console.error(obj);
			},
			info(obj) {
				console.log(obj);
			},
			warn(obj) {
				console.log(obj);
			},
		},
		tls: {
			rejectUnauthorized: false,
			minVersion: "TLSv1.2",
		},
		servername: "posteo.de",
		emitLogs: true,
		disableAutoIdle: true,
		verifyOnly: true,
	});

	await imapFlowClient.connect();
	console.log("after connect");
	await imapFlowClient.logout();
}
```

When using bun, execute the above script with `bun ./path/to/file.ts`.

In my case, I get the following logs:

```
{
  src: "connection",
  msg: "Established secure TCP connection",
  cid: "erf23i15no1o0c1fnv6p",
  secure: true,
  host: "posteo.de",
  servername: "posteo.de",
  port: 993,
  address: "2a05:bc0:1000:80::169:1",
  localAddress: "127.0.0.1",
  localPort: 55720,
  authorized: false,
  algo: "TLS_AES_256_GCM_SHA384",
  version: "TLSv1/SSLv3",
}
{
  src: "s",
  msg: "* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.",
  cid: "erf23i15no1o0c1fnv6p",
  nullBytesRemoved: undefined,
}
{
  src: "s",
  msg: "1 ID (\"name\" \"imapflow\" \"version\" \"1.0.164\" \"vendor\" \"Postal Systems\" \"support-url\" \"https://github.com/postalsys/imapflow/issues\")",
  cid: "erf23i15no1o0c1fnv6p",
  comment: undefined,
}
{
  src: "s",
  msg: "* ID (\"name\" \"Dovecot\")",
  cid: "erf23i15no1o0c1fnv6p",
  nullBytesRemoved: undefined,
}
```

What's suspicious to me: `version: "TLSv1/SSLv3"`, which makes me guess whether my TLS version config on the imapflow client takes effect.

Posteo states on their website, that TLS 1.0 connections will be rejected: https://posteo.de/en/help/how-do-i-set-up-posteo-in-an-email-client-pop3-imap-and-smtp

**Expected behavior**
I expect to see `after connect` in my console eventually.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] server side, so no browser involved
 - Version [e.g. 22] -

**Comment by andris9** [comment]
Does it work with Node?

**Comment by benjaminpreiss** [comment]
> Does it work with Node?

Instead of executing it with bun? let me check.

**Comment by benjaminpreiss** [comment]
Closing this issue as this seems related to bun.
