### ISSUE TITLE
[Deprecation] Plain username & password doesn't work with google

### ISSUE THREAD

**Issue by uzair004** [postalsys/imapflow#218]
**Description**
The code connects to gmail imap using plain username and password however it no longer works.

**To Reproduce**
1. Copy given code for readme
2. Add your gmail credentials
3. Run the code

**Expected behavior**
Code should be able to authenticate to gmail account and return or log the given data i.e messsage

**Screenshots**
<img width="506" alt="Screenshot 2024-09-21 at 7 39 46 PM" src="https://github.com/user-attachments/assets/ac10545a-be24-430f-adc7-bee893757457">

**Desktop:**
 - OS: iOS
 - Browser chrome
 - Version 127.0.6533.120 

**Additional context**
Google require use of OAuth to provide access to its gmail API. It throws invalid credentials error when using plain username and password.

**Comment by andris9** [comment]
Yes, this is expected. As the credentials used are not valid anymore you get an exception.

**Comment by uzair004** [comment]
> Yes, this is expected. As the credentials used are not valid anymore you get an exception.

Update: Actually additional steps are required to setup and use plain username and app password.

Steps:
1. Enable 2FA on email account
2. Generate App password in email account
3. Use that app password for imap auth

P.S: App passwords may not be available for organization accounts.
