### ISSUE TITLE
client.fetch timeout

### ISSUE THREAD

**Issue by upundefined** [postalsys/imapflow#219]
**Describe the bug**
Sometimes client.fetch doesnt return anything, so code is freezes on this line

**Expected behavior**
Some timeout option on .fetch ?

**Screenshots**
![изображение](https://github.com/user-attachments/assets/c0a35f00-3fb9-4a31-a56e-1cd992fd4026)

**Comment by andris9** [comment]
What do you mean it does not return anything? Does it time out because server does not send anything or the server sends an empty response? Also, make sure you are not running any imap commands inside the `for await` loop.
