### ISSUE TITLE
Cannot query data using the SearchObject object, such as the from and subject fields

### ISSUE THREAD

**Issue by CerteasyTeam** [postalsys/imapflow#222]
**Describe the bug**
Hi

I use the subject and from fields to search for invalid in the imapflow @^ 1.0.164 version

**Expected behavior**
Can be searched

**Screenshots**
![微信截图_20241009123019](https://github.com/user-attachments/assets/6e48d286-5baf-490d-9248-375856d43852)

**Env**
 - NodeJS: ^18
 - Imapflow : ^1.0.164

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser: Microsoft Edge
 - Version: 129.0.2792.79

**Comment by andris9** [comment]
ImapFlow passes all search terms to the server for processing. If results are unexpected, then the issue is with the server, not with ImapFlow.
