### ISSUE TITLE
[Feature Request] React compatibility

### ISSUE THREAD

**Issue by ndesgranges** [postalsys/imapflow#223]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the library in a [react native](https://github.com/facebook/react-native) project

**Describe the solution you'd like**
The library requires some node standard modules like [`tls`](https://node.readthedocs.io/en/stable/api/tls/) that are not part of the native React runtime

**Describe alternatives you've considered**
Any library I could find are not actively maintained

So my only options as for now are : 
- use a deprecated library and take all the risks.
- Build myself a React Native library, I could use this as a starting point but I really don't know much about imap that would be very time consuming.
- Implement the imap in a backend server and use it as intermediate which would be bad for performance, maintainability  and security. That would look like `client <-> my intermediate server <-> imap server`

**Additional context**
I'm trying to list emails inside a react native application using imap. (I might need to require sending emails using smtp in the future, but not relevant to this library)

**Comment by andris9** [comment]
React is a front-end framework, and ImapFlow only runs on the back end. You can not use ImapFlow without modules like "net" or "tls"
