### ISSUE TITLE
 uncaughtException: read ECONNRESET Server Crashed | Error is not handled by imap its outside where i define all the logic

### ISSUE THREAD

**Issue by muhammadasadalvi** [postalsys/imapflow#225]
This Error occurred and i am unable to handle this exception i have tried different ways but nothing worked

is there anything which support this or how to handle these type of issue, 

moreover the listerner **exists, error, close** is also creating issue, suppose i trigger service and start idle then then multiple listeners work at the same time and creating mess.

**Comment by andris9** [comment]
It is hard to say what is wrong with this description. You have probably not configured the error handler correctly. ImapFlow is used in production with no issues.

**Comment by muhammadasadalvi** [comment]
Its a general error i have found, its raise when connection interrupted either from client or server, node said this type of exception "unhandledException", it only catch via process.on('uncoughtException',cb)

**Comment by benbucksch** [comment]
If this was an `uncaughtException`, then ImapFlow is not catching some exceptions and not sending them to the connection on'error' handler.

Potential fix: PR #303
