### ISSUE TITLE
How to idle for one mailbox and still load others

### ISSUE THREAD

**Issue by enyo** [postalsys/imapflow#227]
I want to get events for the INBOX.  Whenever a new email arrives I want to handle it. That's easy with the auto idle.

But now I have two other inboxes "trainGood" and "trainSpam". I think that there is no way to listen to all three without creating other clients?

I'm fine with polling them every few minutes, but if I unlock the INBOX, wouldn't I miss out on events about new emails there while I check the training mailboxes? Is there a way to continue listening to the inbox while looking at the emails in other mailboxes?

thanks!

**Comment by andris9** [comment]
Well, TBH, this is why I created [EmailEngine](https://emailengine.app/). While ImapFlow handles the IMAP protocol layer for EmailEngine, the connection management and polling logic are implemented on EmailEngine's side.

Although you can establish a separate connection for each mailbox folder, be aware that email providers often limit the number of concurrent connections per account. For example, Gmail allows a maximum of 15 simultaneous connections per email account. If the user's email clients on their phone and desktop already consume 10 connections, you would have only 5 connections remaining for that user.
