### ISSUE TITLE
Handling Reconnection in a NextJS API Route

### ISSUE THREAD

**Issue by leo7418** [postalsys/imapflow#228]
Hello,

I'm using ImapFlow version 1.0.165 with NodeJS 20.18.0 in a NextJS (15.0.2) environment, specifically within an API route that returns a streaming response. When the IMAP connection is lost, the stream also gets interrupted, and I’m looking for guidance on implementing reconnection logic to avoid this issue.

**Problem:**

When the IMAP connection is closed, it interrupts the streaming response from the API route, rather than automatically handling a reconnection. The goal is to maintain a stable stream even when the IMAP connection drops.

The `onClientClose` function is indeed called when the connection is lost. I also attempted to add a `throw` within `onClientClose`, hoping that it would enter a catch block and allow the loop to continue, but this didn’t work as expected.

**Code Sample:**

Here’s the code I’m using to manage the connection and handle messages:

```typescript
let currentMessagedata: FetchMessageObject;

const onClientClose = () => {
  console.trace("Client closed, reconnecting...");
  messagesData.unshift(currentMessagedata);
  this.connect();
  // throw 'retry';
};

this.safeClient.addListener("close", onClientClose);

while (messagesData.length > 0) {
  currentMessagedata = messagesData.shift()!;

  try {
    const message = {
      ...currentMessagedata,
      bodyStructure: messages.find((m) => m.uid === currentMessagedata.uid)!.bodyStructure,
    };

    const textContent = await this.getTextFromPart(message.seq, message.bodyStructure);

    yield {
      uid: message.uid,
      seq: message.seq,
      envelope: message.envelope,
      textContent,
    };
  } catch (err) {
    console.log("Error reading message, retrying...");
  }
}

this.safeClient.removeListener("close", onClientClose);

...

// In the same class
connect = async () => {
  this.client = this.createClient();

  try {
    await this.client.connect();
  } catch (err) {
    console.error("Failed to connect to mail server:", err);
    throw err;
  }
};
```

The `getTextFromPart` function calls `this.safeClient.download`, so any disconnection impacts both the message handling and the streaming response.

**Questions:**

1. **How can I implement reconnection logic that gracefully resumes the stream after a lost connection?**
2. **Is there a recommended way to maintain the streaming response during reconnection attempts in a NextJS API environment?**

Any guidance or examples on best practices for handling reconnection with ImapFlow in this context would be greatly appreciated!

Thank you for your assistance!

Best regards,  
Lhuile Léo

**Comment by andris9** [comment]
You can not reconnect, and you can not resume a disconnected session. You need to create a new ImapFlow instance and start over. For more complex tasks, I suggest using [EmailEngine](https://emailengine.app/) instead.

**Comment by leo7418** [comment]
Thank you for the suggestion, but unfortunately, EmailEngine is much too expensive for the scale of my intended usage.

As for reconnecting, I’m actually not trying to resume a disconnected session. In my example, I am indeed creating a completely new instance of ImapFlow when the connection drops. My question, then, is why this approach doesn’t seem to work: the code execution doesn’t continue as expected, and instead, the process halts as soon as the connection is lost.

Could you clarify why creating a new instance doesn’t allow the process to proceed, and what might be causing the process to stop altogether when the connection closes?
