### ISSUE TITLE
When trying to fetch source imapflow hangs.

### ISSUE THREAD

**Issue by enyo** [postalsys/imapflow#230]
Whether I do this:

```js
let messages = client.fetch(`1:*`, {
  source: true,
})
for await (let message of messages) {
  // Never reached
}
```

or, fetching the uids first and then do individual fetchOne like this:

```js
let messages = await client.fetchOne(uid, {
  source: true,
}, { uid: true })
// Never reached
```

imapflow always just hangs there, and it is never resolved. If I remove the `source` attribute and just fetch envelope for example it works.

Do you have a tip of what that could be? I'm using Apple Mail email provider.

**Comment by enyo** [comment]
It also hangs if I try to use `download`

**Comment by enyo** [comment]
Thanks for the swift response @andris9 but I'm pretty sure that's not the case since just removing `source: true` from the config works fine. I have added a `source: {maxLength: 20}` to test, and that works (but the message is cut off of course). I'm starting to suspect that it's due to me using Deno, and the TCP Stream implementations of Deno are not fully compatible with the node ones?...

**Comment by andris9** [comment]
Oh, that explains. Deno and Bun are not supported. It might work but probably does not. As soon as you get into more complex TCP and TLs wrangling the differences between different runtimes raise to the ground.

**Comment by andris9** [comment]
I guess what happens in your case is that when the data responded to the FETCH exceeds stream buffer size it breaks the async generator and ends up in a deadlock (second chunk is never read from the TCP socket). This would explain why smalles responses go through.

**Comment by enyo** [comment]
Yes that's exactly what happened. I just switched to node now and it works fine.

**Comment by meepleschubser** [comment]
Had the same problem today until I found this post.
Unfortunately, I can't just switch to node. Are there any plans to support deno in the future?

**Comment by andris9** [comment]
No plans to support anything else than Node. It would be too much work to find all these edge cases with other runtimes while I only use Node myself.
