### ISSUE TITLE
Property 'exists' does not exist on type 'boolean | MailboxObject'.

### ISSUE THREAD

**Issue by EranStockdale** [postalsys/imapflow#232]
**Describe the bug**
`@types/imapflow`: `Property 'exists' does not exist on type 'boolean | MailboxObject'.`
Unsure what else to say here.

**To Reproduce**
Here's my code:
```typescript
import { NotifierBase, NotifierConfigBase } from "../types/Notifier";
import { ImapFlow, MailboxLockObject, MailboxObject } from 'imapflow';

export interface IMAPConfig extends NotifierConfigBase {
    host: string;
    port: number;
    secure: boolean;
    username: string;
    password: string;
    inbox?: string;
};

export class IMAPNotifier extends NotifierBase {
    private client: ImapFlow;

    constructor (id: string, private config: IMAPConfig) {
        super(id);
        this.client = new ImapFlow({
            host: this.config.host,
            port: this.config.port,
            secure: this.config.secure,
            auth: {
                user: this.config.username,
                pass: this.config.password
            }
        });
    };

    async refresh(): Promise<boolean> {
        await this.client.connect();

        let lock: MailboxLockObject = await this.client.getMailboxLock(this.config.inbox ?? 'INBOX');
        let mailbox: boolean | MailboxObject = this.client.mailbox;

        try {
            let message = await this.client.fetchOne(this.client.mailbox.exists, { source: true });
        } finally {
            lock.release();
        }

        await this.client.logout();
    }
};
```

**Expected behavior**
Correct intellisense / autocomplete.

**Screenshots**
![image](https://github.com/user-attachments/assets/7364aa99-52a8-40ea-b874-e9ebb698025b)
![image](https://github.com/user-attachments/assets/037629ab-3874-4c5c-9032-9530b664456c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 130.0.6723.92

**Additional context**
Node v20.12.1
Using `tsx` v4.19.2 for executing the Typescript files.
Imapflow v1.0.19

**Comment by andris9** [comment]
These types are maintained by community, these are not part of ImapFlow. So you need to contact whoever maintans the types package https://www.npmjs.com/package/@types/imapflow

**Comment by EranStockdale** [comment]
Ah okay, apologies!

**Comment by Twister42** [comment]
I know this is closed, but still asking because I'd really like to understand 'why' it's done this way.

Whatever the types says, it says so because it's what you defined in your code : `MailboxObject | boolean`

Why not `MailboxObject | undefined` ?
Would be easier for typescript and it would still work with a simple in both JS and TS `if (client.mailbox)` ?
Am I missing something?
