### ISSUE TITLE
Allow to enforce STARTTLS - Prevent downgrade attacks

### ISSUE THREAD

**Issue by benbucksch** [postalsys/imapflow#242]
This is a security bug report. I file it publicly, because the problem is well-understood in security circles and any competent security tester will try this.

### Reproduction
1. Configure an IMAP server to use STARTTLS.
2. Connect.
3. Attack the user with a fake IMAP server (manipulating DNS, manipulating network at IP level, etc.pp)
4. The attacker's IMAP server does not advertize the `STARTTLS` IMAP `CAPABILITY`

### Actual result
* Step 2: All seems to work under normal circumstances. The connection is encrypted using TLS.
* Step 4: ImapFlow connects to the server without encryption.
* The attacker can read and steal the password.
* The attacker can use the password to authenticate to the real IMAP server, and get all the victim's mail.
* The attacker can use the same password for other services, e.g. for Windows login or other privileged services, depending on the user account.
* The fake IMAP server of the attacker can serve as proxy to the real server, so the user might never notice anything being wrong.

### Expected result
* Step 2: Connection works
* Step 4: Connection fails, with a clear error message.
* Once a server is known to support STARTTLS, the client should *insist* on it and enforce it.

### Security
STARTTLS for opportunistic encryption - meaning: Use it when it's there, otherwise connect without it - is now considered insecure and dangerous, because it gives a false sense of security. It seems to work in normal circumstances, but fails in the face of a serious attack. See e.g. the FOSDEM talk Feb 2024 about it, and lots of research papers referenced there.

### Clients
For security, Thunderbird and my email client only offer the 3 modes:
* Always direct/implicit TLS (default)
* Always STARTTLS, never fallback (legacy servers only)
* Never TLS (with a big fat red warning; if nothing else works)

**Comment by andris9** [comment]
It is incredibly rare to see a server with STARTTLS in the context of ImapFlow. ImapFlow only exists to serve EmailEngine.app (it was originally part of EmailEngine, but I extracted it into a separate, open-source module). EmailEngine mainly manages so-called business emails, e.g., MS365, Gmail, and so on. All mainstream IMAP services use port 993 with TLS. I don't know a single service that only provides port 143 with or without STARTTLS. I would even say that there are zero such servers (self-hosted test and development servers do not count as these are never targets for EmailEngine). As such, I don't see any issues with the current behavior.

**Comment by benbucksch** [comment]
Fixed by PR #243

**Comment by benbucksch** [comment]
* As author of the ISPDB that Thunderbird uses, I know that there are plenty of servers from various ISPs that speak only STARTTLS.
* The problem here is that the default config is vulnerable to a well-known security bug. You may think that you're not affected. But everybody who was vulnerable to the bug thought the same.
* I've created a fix for it. It's non-intrusive, follows the existing code pattern, a relatively small change, and fixes the bug. And it even preserves the default behavior.
* What's the harm in fixing a security bug, even if you think it doesn't apply to you?

**Comment by andris9** [comment]
Well, yes, I guess that there is no reason to reject the PR.

**Comment by benbucksch** [comment]
Thank you :-)
