### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by opahopa** [postalsys/imapflow#38]
Would like to see the proxy support functionality, as none of the other nodejs imap clients have it

Example:
```
const client = new ImapFlow({
    host: 'imap.somehost.com,
    port: 993,
    secure: true,
    auth: {
        user: 'someaddr@mail.com,
        pass: '1q2wedrf'
    },
    proxy: {
        host: '1.1.1.1', 
        port: 12345,
        type: 'http',              // http/s  socks4  socks5
        username: 'user', 
        password: 'pass' 
    }
});
```

**Describe alternatives you've considered**
`imap`, `imap-simple`, `imap-simple-with-proxy` (no http/s proxy support), `emaljs-imap-client`

**Comment by andris9** [comment]
There hasn't been much demand for proxies and it is a real pain to deal with so I have not implemented it.

**Comment by andris9** [comment]
Proxies are now supported by providing a proxy URL

```js
const client = new ImapFlow({
    host: 'ethereal.email',
    port: 993,
    secure: true,
    auth: {
        user: 'garland.mcclure71@ethereal.email',
        pass: 'mW6e4wWWnEd3H4hT5B'
    },
    proxy: 'https://proxy-host:1080'
});
```

ImapFlow supports HTTP CONNECT (https:// and https://) and SOCKS (socks://, socks4://, socks5://)
