### ISSUE TITLE
download for sendmail IMAP server not working

### ISSUE THREAD

**Issue by michaelmok2021** [postalsys/imapflow#55]
Can imapflow download attachements from sendmail (dovecot)'s IMAP server? 

My example below. the process hangs at the 'if (content)' line and evetually after 30 seconds our test (via tap) timesout.

```javacript
let unseenCount = await client.status('INBOX',{messages: true, uidValidity: true, unseen: true })
        logger.info('unseenCount returned ', unseenCount)
        if (unseenCount.messages > 0) {
            logger.info('unseenCount returned ' + unseenCount.messages + ' messages')
            for await (let message of client.fetch('1:*',
                {uid: true, envelope: true, bodyStructure: true})) {
                const uid = message.uid
                logger.info(`fetchMany returned UID ${uid} : ${message.envelope.subject}`);
                console.log('body structure ', message.bodyStructure.childNodes)
                let {meta, content} = await client.download('' + uid, '1', {uid: true});
                if (content) {
                    console.log('body part meta ', meta)
                }
            }
     }
```

**Comment by andris9** [comment]
The thing to consider with IMAP is that it is single threaded, you can issue a single command at a time and you have to wait for the previous command to finish before you can issue the next one. So what happens in your case is that ImapFlow is still processing the `client.fetch('1:*'...` command so when you  run `client.download` then it will wait forever as the previous IMAP command is not yet finished (and it does not finish until the `for await` loop has finished).

The solution would be to run the loop twice. First you get and cache the message uid's and bodyStructure's and once this loop is done, you run a second loop against your cached list to download attachments.

**Comment by michaelmok2021** [comment]
Thanks Adris for calling out about the need to wait for the previous command to finish before issuing the next one.  Running the loop twice should work.
