### ISSUE TITLE
"exists" event handler not being invoked

### ISSUE THREAD

**Issue by phi1ipp** [postalsys/imapflow#57]
**Describe the bug**
It looks like there is an issue with "exists" handler invocation, whenever a new email arrives to a subscribed mailbox

**To Reproduce**
I attached my backend log with detailed descriptions of significant steps https://gist.github.com/phi1ipp/605b519f9d7f2a035461596d82fcc848

**Expected behavior**
Whenever a new email arrives in the mailbox, which a client is subscribed on, there should be an invocation of "exists" handler

I'd appreciate if you can provide a clue for a possible issue in my processing, but based on the detailed logger info from the library, server responds as expected, yet client library does not process the events accurately.

Thank you in advance!

**Comment by andris9** [comment]
What server is this? Is there an untagged FETCH after EXPUNGE or is it plain EXPUNGE without the updated message count?

**Comment by phi1ipp** [comment]
@andris9 , thx for looking into it. It's Communigate Pro. As for the second question, I'm afraid I'm not that well versed with IMAP implementation details.

Is there any diagnostic I can provide you with from a server side, which could help to troubleshoot it? It's internal server luckily so I have access to the logs through our admin.

**Comment by andris9** [comment]
It seems that ImapFlow is not completely compatible with that server. It is proprietary so I haven’t been able to test against it. Based on your log I think I have a hunch of what needs improving, I’ll look into it.

**Comment by andris9** [comment]
Could you try v1.0.68 and see if it made things better or not

**Comment by phi1ipp** [comment]
Thank you, @andris9! It's working fine now
