### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by vincent-tr** [postalsys/imapflow#58]
**Describe the bug**

I'm using ImapFlow to login into a mail box, and in a long-running process fetch each new mail.
After some time on running, it seems that node process is taking more and more memory.
After a bit of debugging, it seems that at some point `ImapFlow.requestTagMap` is becoming very big (>50000 items inside)

Here is the way I fetch messages:

```javascript
for await (const msg of imapflow.fetch(pattern, { envelope: true, bodyStructure: true, bodyParts: ['text'] })) {
 // process message
}
```

**Environment**
 - OS: linux
 - Node: v14.17.6

**Comment by andris9** [comment]
`requestTagMap` should be at all times near zero as whenever a command is finished, it is removed from the map. You can see the size like this:

```
console.log(`requestTagMap size: ${imapflow.requestTagMap.size}`);
```

Could you have some special condition that does not allow these commands to be properly cleaned up? Could you provide a simple test case (a minimal script that uses ImapFlow) that I could run myself and where `requestTagMap` would keep growing?

**Comment by vincent-tr** [comment]
Thanks for your answer.

After more investigations, it seems that the problem is on my side: due to a bug, I was calling `for await (const msg of imapflow.fetch(...` a lot of time at the same time.

Sorry for the noise, and thanks for your support.
