### ISSUE TITLE
Gmail and Application Password failing to open mailbox

### ISSUE THREAD

**Issue by ramiroaisen** [postalsys/imapflow#59]
**Describe the bug**
Imapflow is failing to open a mailbox in a gmail account with Application Password login.
The client is passing the `connect` stage check but failing to open a mailbox, it returns `Command failed` error with no more info about whats going on than that.

**To Reproduce**
1. instantiate Imapflow with gmail and Application Password settings 
2. Connect with `await client.connect()`
3. Open any mailbox, eg: `client.mailboxOpen("INBOX")`;
4. Throws a `Command failed` error.

**Expected behavior**
Open the mailbox as normal or a detailed error message

**Desktop (please complete the following information):**
 - OS: Fedora 34 Linux
 - NodeJS: 16.9.0

**Comment by andris9** [comment]
Do you have the IMAP logs? Hard to say what’s going on without seeing what the client and server are sending to eachother
