### ISSUE TITLE
"Unexpected Token" with Vue (Webpack)

### ISSUE THREAD

**Issue by SebastianThomas** [postalsys/imapflow#61]
**Describe the bug**
I tried to use ImapFlow as shown in the basic example (in the README) with vue.js. When I try to compile the app, I am getting the error you can see below. 
It seems like `static` is not supported in this context, doesn't it? 

I have tried to find solutions to this problem, but all solutions are correlated with React (where you can find a webpack config file, which I have not found in vue yet...). 

**To Reproduce**
1. Create a new vue app
2. Add a file called `MailService` in `src/services` directory. 
3. Paste the code from the example. (add a function around it which you module.export =)
4. Import this MailService file into a component and call it. 
5. Run `npm run serve` or `npm run build`. 

**Error**
```
 ERROR  Failed to compile with 1 error                                        4:15:37 PM

 error  in ./node_modules/imapflow/lib/imap-flow.js

Module parse failed: Unexpected token (103:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|      * @static
|      */
>     static version = packageInfo.version;
| 
|     /**

 @ ./src/services/MailService.js 1:21-40
 @ ./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/Mailbox.vue?vue&type=script&lang=js
 @ ./src/components/Mailbox.vue?vue&type=script&lang=js
 @ ./src/components/Mailbox.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js
```

**Comment by SebastianThomas** [comment]
Do you know how I can add a loader that supports this syntax (since I created my project yesterday I suppose there should be a fix for the current version of all packages)? Thanks in advance!

**Comment by andris9** [comment]
ImapFlow is a server side module, you can't use it in the browser. And server side modules usually do not need any kind of bundling, so I haven't considered any bundling support. If you really do need it then I guess you could use Babel to transpile it into a more older version of Ecmascript before bundling.

**Comment by SebastianThomas** [comment]
Okay, thank you! Then I will write a backend server that uses `imapflow`, thanks again!
