### ISSUE TITLE
Support sort option in fetch

### ISSUE THREAD

**Issue by ramiroaisen** [postalsys/imapflow#62]
Is there a standard way to sort messages in `fetch`? could this be supported by imapflow?

I'm willing to help in the implementation of this feature.

**Comment by andris9** [comment]
IMAP servers sort emails by UID number. There is also a SORT extension (rfc5256) but it does not have enough support by IMAP servers that it would make sense to use it with ImapFlow – SORT and ESORT are usually supported on self hosted Dovecot installations but I don't think that any of the large email services (Gmail etc) support it.
