### ISSUE TITLE
Download large files

### ISSUE THREAD

**Issue by Niki2k1** [postalsys/imapflow#65]
**Describe the bug**
If I try to download an Email Attachement (PDF Files to be specific) larger than approximately 1MB (not completely sure) I only get data until a certain point.

I try to download the files like this:
```js
if (attachement.type === 'application/pdf' || attachement.type === 'application/octet-stream') {
  const path = `${__dirname}/../data/${seq}`
  if (!fs.existsSync(path)){
    fs.mkdirSync(path);
  }
  const stream = fs.createWriteStream(`${path}/attachement.pdf`)
  content.pipe(stream);
  stream.on('finish', () => {
    resolve(fs.readFileSync(`${path}/attachement.pdf`))
  })
  stream.on('error', (err) => {
    reject(err)
  })
}
```

The attachement looks like this:
```js
{
  part: '2',
  type: 'application/pdf',
  parameters: { name: 'test.pdf' },
  description: 'test.pdf',
  encoding: 'base64',
  size: 2859132,
  disposition: 'attachment',
  dispositionParameters: {
    filename: 'test.pdf',
    size: '2093063',
    'creation-date': 'Tue, 26 Oct 2021 12:44:00 GMT',
    'modification-date': 'Tue, 26 Oct 2021 12:46:50 GMT'
  }
}
```
The file I get after its written is only 191568 Bytes large

If I open the file as text in VSCode and compare it with the original pdf I see that there is data missing.

Any Ideas?

Thanks
Niklas

**Comment by edamazzio** [comment]
Hey @Niki2k1, I'm having the same issue trying to obtain PDF files. Were you able to solve this?
