### ISSUE TITLE
Fetching messages with text preview

### ISSUE THREAD

**Issue by arqo123** [postalsys/imapflow#67]
Hello there! It's really great to use this library - great work!.

I have on my app similar view of email list, as it is in gmail. And as on gmail, i near to the "Topic" i have a part of the message - lets call it "preview part".
To build that list view, im fetching some range of messages with fetch() method. That gives me 95% of data, that i need, however to build preview part, i need to:

1. Found proper body part, that contains text/html or text/plain
2. For each message download that part with download() method
3. Exclude begging of message with some parsing. 

I believe, that there is an easier, and more efficient way to reach this. Any clue? 

![thread-3991781-1415021831237171843](https://user-images.githubusercontent.com/26055043/139501295-7b02e933-0d93-4fc2-9b92-4a36024dd4fa.jpg)

**Comment by raghavyuva** [comment]
@arqo123  you'll get the subject with the fetch method, to list out /preview you just need that subject and while displaying a particular message you may need to use the parser, so your 3rd point says that you don't require a parser and you are trying to do it with downloading a message.

i suggest you to do in this way,
1) list out messages with fetch() method,passing source as true in the parameter,
2) for a particular message use some parser say **[mailparser](https://www.npmjs.com/package/mailparser)**.
3) you'll get an object containing the text/html or a text/plain.

hope it might help for you

**Comment by arqo123** [comment]
Hello @raghavyuva ! Thanks for your respond! 

At the begining i've tried with the mailparser, but i've tested it one more time, and it is not a perfect tool. When parsing messages with it, it keeps some html tags and decorators from header - as fonts imports. 
And for me there is one more problem  - in your approach i need to download the whole messages - right with the attachments.  For a small messages it was faster than my solution, but when i've list messages with attachments it was few times slower :(  

![Screenshot_1017](https://user-images.githubusercontent.com/26055043/139582224-4156b7fb-c702-4a23-99f1-e8e1dd354359.png)

**Comment by CreatorEzio214** [comment]
Like @raghavyuva already said: The best way for this is to use a parser ([mailparser](https://www.npmjs.com/package/mailparser) is very good for that)

With mailparser you can do this then:

```js
const simpleParser = require('mailparser').simpleParser;

//later when you fetch e-mails
let lock = await client.getMailboxLock('INBOX');
for await (let message of client.fetch('1:*', { source: true; } )) {
    let message_preview = await simpleParser(message.source);
    message_preview.text; //<-- this gives you only text without any html tags
    message_preview.html; //<-- this gives you text with html tags
}
```

**Comment by andris9** [comment]
You have two options
* Either download the full message and parse the text out of it (easier but very slow as downloading all the attachments just to get a text preview would take a lot of time)
* Do it in 2 steps, first fetch the bodystructure, identify text nodes from int and then fetch all those nodes. IMAP also allows you to specify a limit, so you could for example download only the first 2048 bytes of each text node which should be enough even for HTML content for the actual text to appear

If you want to see how to properly handle the second method, check out how [EmailEngine](https://github.com/postalsys/emailengine) handles this as it also uses ImapFlow under the hood. If you set up webhook notifications for new messages and select to include the text content (configuration->webhooks page) then EmailEngine fetches bodystructure first and then text nodes as well. Then it also compiles these text nodes into actual blobs of text and pushes it to a webhook URL.
