### ISSUE TITLE
messageDelete with Gmail

### ISSUE THREAD

**Issue by CreatorEzio214** [postalsys/imapflow#69]
I got the following code for deleting a mail

```js
async function deleteMail(mail) {
  try {
    await client.connect();
    let lock = await client.getMailboxLock(current_mailbox);
    await client.messageDelete({uid: mail.uid});
    lock.release();
    await client.logout();
  } catch(err) {
    console.log(err);
  }
}
```

The problem is that this doesn't delete the mail it moves it to "All E-Mails" instead of "Trash".

So I got following questions:

1. How to move a mail to trash (whats the mailbox path in gmail for it?)
2. How to delete a mail completely

**Comment by andris9** [comment]
This is Gnail specific. Deleting an email only removes the "label" from it and if no labels remain, it gets "archived" by only being shown in the All Mail folder. For actual deletions you either have to move the message to Trash or delete it from the All Mail folder, not from Inbox.
