### ISSUE TITLE
Bug using seq option (ex.: seq:"*") alongside other SearchObject options

### ISSUE THREAD

**Issue by alexauch01** [postalsys/imapflow#72]
**Describe the bug**
It seems there is a bug when a fetch call using the seq option ("\*", "1,2,3", etc. EXCEPT "1:*" )is used ALONGSIDE other options in the documentation (see screenshot attached).

**To Reproduce**
Try to run the snippet code in the doc using this fetch call: client.fetch({seq:"*", from:"email@domain.com"}, {...})
Replace "email@domain.com" by an email such as the client.fetch({from:"email@domain.com"}, {...}) alone give you several results.

**Expected behavior**
The call client.fetch({seq:"\*", from:"email@domain.com"}, {...}) should return the newest email received from email@domain.com but the result is empty. 

However if you call client.fetch({from:"email@domain.com"}) it gives non empty results. Also client.fetch({seq:"1:\*", from:"email@domain.com"} ) give non empty results and the seq:"*" option used alone works as expected.

But client.fetch({seq:"*", from:"email@domain.com"}) or again client.fetch({seq:"1,2,3", from:"email@domain.com"}) will always give empty results no matter your other options (see screenshot) are.

<img width="1101" alt="Screen Shot 2022-02-28 at 5 10 08 PM" src="https://user-images.githubusercontent.com/100636030/156068203-72f5dd4c-247b-472e-8893-774c75c993bb.png">

**Comment by andris9** [comment]
Some servers do not recognize `"*"` as a valid sequence, you can only use it in a range (`"x:*"`). The query terms are _AND_ terms, which means that both conditions must match - sequence number must be in the requested range and the email address must match as well. Could you provide the actual IMAP transaction log, eg the commands sent and responses received from the server, so I could check if the query is generated somehow invalidly?
