### ISSUE TITLE
I am trying to use proxy, but it showing: Error: Failed to setup proxy connection

### ISSUE THREAD

**Issue by harunurkst** [postalsys/imapflow#73]
my config 

```
let config = {
    host,
    port,
    secure,
    tls: {
        rejectUnauthorized: false
    },
    auth: {
        user,
        pass
    },

    proxy: 'user:pass@gate.smartproxy.com:7000'
};```
but it's showing this error: `Error: Failed to setup proxy connection`   
my proxy is working fine with curl

**Comment by andris9** [comment]
You have to specify the protocol in the url (eg. `socks5:`). Additionally, if you are using a HTTP proxy then that proxy must support the `CONNECT` method.

**Comment by harunurkst** [comment]
If I specify "https" it shows this error: `'ERR_SSL_WRONG_VERSION_NUMBER'`
for http it shows this error:

**Comment by andris9** [comment]
You seem to be using an HTTP proxy, not HTTPS, and that proxy returns you 403 response which might mean that either the credentials are wrong or (more probably) your proxy does not support tunneling. Try to get the same proxy working with some other application first, eg. with Thunderbird, to see if it works or not.
