### ISSUE TITLE
Special character & should be escaped

### ISSUE THREAD

**Issue by jerome-fox** [postalsys/imapflow#74]
**Describe the bug**
If a folder contains an `&` character, we cannot open the folder.
The code of [normalizePath](https://github.com/postalsys/imapflow/blob/master/lib/tools.js#L26) converts this character without any possibility to escape it.
When the line is commented, the folder can be opened.

**To Reproduce**
1. Create a folder with an `&` (for example: AT&T)
2. List the boxes `list()`
3. Try to open the folder `getMailboxLock('AT&T')`
4. See error `'B NO [NONEXISTENT] Unknown Mailbox: "AT㸚" (Failure)'`

**Expected behavior**
We should be able to escape this character and the `list()` method should return the escaped path.

**Desktop:**
 - OS: MacOSX M1
 - Browser: NodeJS
 - Version: 16

**Comment by andris9** [comment]
Seems to be a bug, will look into it

**Comment by malefique** [comment]
Same for passwords with %, I'm getting "Invalid login or password" all the time with passwords contains % char.

**Comment by andris9** [comment]
@malefique what server is this? Using % should be valid in general. The issue with & already got fixed btw, forgot to close this ticket

**Comment by malefique** [comment]
@andris9, Hi! I'm trying to log in with those credentials: 
login yuywxyhjrx@rambler.ru 
pass dvwoedsrnrFL!-$@%13704
server imap.rambler.ru
port 993
secure true

You can check that credentials are valid at mail.rambler.ru, imap also avaialable for it: https://mail.rambler.ru/settings/mailapps

**Comment by andris9** [comment]
Thanks, I’ll test it out later today (removed credentials from your comment)

**Comment by andris9** [comment]
@malefique Does it work with another password? I tried to test the credentials you provided and was not able to log in to IMAP at all.

1. I used the common `LOGIN` authentication method - server responded with `NO Invalid login or password`
2. I used the `AUTH=PLAIN` method that the server also supports, the server responded with `NO Invalid login or password`
3. I logged in to the web interface and toggled "Доступ к почтовому ящику с помощью почтовых клиентов." off and on - no change
4. Tried to log in using Thunderbird - no success, username or password incorrect

As I was able to log in to the web interface then the credentials I used were correct.

**Comment by malefique** [comment]
@andris9, yeah, I've got 4k accounts like I mention before, I'm getting response `NO Invalid login or password` when password contains `%`. I assume it can be some "feature" from rambler, I was able to log in to the web interface also, which got me a lil bit confused. Other accounts work fine.

**Comment by Summaw** [comment]
> 

So I figured out that in the rambler accounts you must go to settings and allow acess to the mailbox using mail clients.
Hope this helps 👍 

![image](https://user-images.githubusercontent.com/98126132/204709652-5ff21263-53fb-4f6e-8cc0-d2b492ae3813.png)
