### ISSUE TITLE
How to set ImapFlow to UID mode?

### ISSUE THREAD

**Issue by bluepuma77** [postalsys/imapflow#76]
Is it possible to use ImapFlow with UIDs instead of message sequence numbers? I always feel more secure with UIDs as they won't change. If I use sequence numbers for processing in a script, while someone moves messages around in the mailbox, I might process the wrong message.

My use case:
1. Find all messages with UID in INBOX with header 'X-Save-Sent: 1'
2. Move those messages to 'Sent' folder by UID

**Comment by andris9** [comment]
You can use UIDs by setting `{uid: true}` option

```
let result = await client.messageMove('123', 'Trash', {uid: true});
```

See the `options` argument in ImapFlow [documentation](https://imapflow.com/module-imapflow-ImapFlow.html#messageMove).
