### ISSUE TITLE
Way to break out of fetch while keeping connection and locks

### ISSUE THREAD

**Issue by tiagoroldao** [postalsys/imapflow#79]
**Is your feature request related to a problem? Please describe.**
Currently, using fetch to look for a message can mean not needing to use all the messages retrieved in the fetch response. There isn't, however, a way to cleanly return from a fetch without throwing, as otherwise the connection hangs while waiting for `onUntaggedFetch` hooks to be called.

**Describe the solution you'd like**
`throw`ing the async generator will release the connection, as `close` is called on error. The same should happen on `return`, without `close` but with a clean closing of the FETCH action.

**Describe alternatives you've considered**
Current solution used:
```typescript
        const lock = await this.client.getMailboxLock('INBOX');
        let message: IteratorResult<FetchMessageObject, never> | undefined = undefined;
        try {
            const fetcher = this.client.fetch('1:*', { source: true });
            do {
                message = await fetcher.next();
                    if (tester(message.value)) {
                        // We need to throw (and kill connection) otherwise there is no way to "clean" the socket
                        await fetcher.throw('').catch(() => undefined);
                        break;
                    }
            } while(!message.done);
        } finally {
            // this is meaningless, as the action, by design, needs to kill the connection
            lock.release();
        }
        return message?.value;
```

**Comment by andris9** [comment]
The `fetch` method expects you to process all the messages before you can continue. The IMAP server will send all the messages you requested, and these must be processed one way or another.

ImapFlow was built for [EmailEngine](https://emailengine.app/), and there is no use case in EmailEngine where a running fetch command needs to be terminated. It is also very straining for the server if you list messages as you do. Also, if you are using Gmail, then this listing will count against your daily download quota of 2.5GB even if you close the connection while receiving the data. If you only need a specific message, it is better to use a search call instead.
