### ISSUE TITLE
Gmail connection

### ISSUE THREAD

**Issue by ArgtimZ** [postalsys/imapflow#81]
**Describe the bug**
So less secure apps are now not anymore supported by Google and that's why my old code won't connect
anymore to gmail IMAP. Is there a way to connect to gmail IMAP with OAuth 2.0 for example or will there
be a more secure way to connect to gmail IMAP in the future versions of imapflow?

**To Reproduce**
1. Try to connect to google IMAP with only email and password using imapflow
2. See authentication error even with right credentials 

**Desktop (please complete the following information):**
 - OS: Windows/macOS
 - Browser Electron (Chromium)
 - newest version

**Comment by andris9** [comment]
Yes, imapflow supports OAuth2, see the `auth.accessToken` option in the [docs](https://imapflow.com/module-imapflow-ImapFlow.html).

EmailEngine uses imapflow to connect to OAuth2 accounts, you can read how to set up OAuth2 with EmailEngine here (the same applies to imapflow as well): https://docs.emailengine.app/setting-up-gmail-oauth2-for-imap-api/
