### ISSUE TITLE
MessageStructureObject.parameters is an object, but typed as string

### ISSUE THREAD

**Issue by nik-lampe** [postalsys/imapflow#82]
Like the title says, the parameters property of the MessageStructureObject is typed as String, but in my case it's an object

```
for await (const message of messageIterator) {
  for (const part of message.bodyStructure.childNodes) {
    console.log(part)
  }
}
```

in my case this yields (amongst other parts):

```
{
  part: '2',
  type: 'application/pdf',
  parameters: { name: 'Pol_XYZ.pdf' },
  encoding: 'base64',
  size: 416118,
  disposition: 'attachment',
  dispositionParameters: { filename: 'Pol_XYZ.pdf' }
}
```

Is this a bug? Or am I missing something?

**Comment by andris9** [comment]
The docs state that it's an object: https://imapflow.com/global.html#MessageStructureObject where do you get it has to be a string?
<img width="994" alt="Screenshot 2022-08-11 at 14 38 00" src="https://user-images.githubusercontent.com/132242/184125246-8eeab0b3-c9ca-4115-a2ed-b019c7cf586d.png">
