### ISSUE TITLE
emitLogs option does not work

### ISSUE THREAD

**Issue by dchicchon** [postalsys/imapflow#84]
**Describe the bug**
Using the option `emitLogs`: false does not work.

**To Reproduce**
1. Install dependency. 
2. Set connection as you would with a regular email with emitLogs false
```js
const {ImapFlow} = require('imapflow')
const options = {
            // your options here,
            emitLogs: false
        }
const imap = new ImapFlow(options)
```
3. Logs show up in the console

**Expected behavior**
Expect that logs do not show up in the console unless `emitLogs: true`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Apple M1
 - Browser: chrome
 - Version: 1.0.107

**Comment by andris9** [comment]
`emitLogs:true` means that you can use `imap.on('logs', handler)`. By default tgat event is not emitted.
