### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by tyzion** [postalsys/imapflow#89]
Hi, is it possible to add a connection timeout property on client.connect()?

Because every time the port is wrong before I get an answer I have to wait for 30-40 secs (or more, I didn't count them)
It could be a property added to the options for creating the client instance, something like **timeout**  or **connectionTimeout** that takes time in milliseconds

`const client = new ImapFlow({
            ...,
            connectionTimeout: 5000
        });
`

Thanks,
tyzion

**Comment by andris9** [comment]
Added `connectionTimeout` option https://imapflow.com/module-imapflow-ImapFlow.html
