### ISSUE TITLE
add connect - timeout  parameter

### ISSUE THREAD

**Issue by DeHby1024** [postalsys/imapflow#90]
Hello, when I use the wrong IP/PORT, the waiting time for await connect will be very long
I used the following scheme early on
```
      await Promise.race([
        delay(5000).then(() => {
          throw new Error("connect timeout");
        }),
        this.m_imap.connect(),
      ]);
```

But obviously that doesn't prevent the connect promise from continuing to execute
After looking at the source code, I found
`const CONNECT_TIMEOUT = 90 * 1000;`
I want it to be a parameter to connect function

**Comment by andris9** [comment]
Added `connectionTimeout` option https://imapflow.com/module-imapflow-ImapFlow.html
