### ISSUE TITLE
fetchOne not working when filtering by header

### ISSUE THREAD

**Issue by jprealini** [postalsys/imapflow#91]
**Describe the bug**
Not sure if this is a bug or me passing the parameters incorrectly, but I found examples of this in some posts even here... I am trying to run fetchOne against Ethereal like this (In a prior step I send an email to the account, and save the messageid returned)

message = await client.fetchOne({ header: { "Message-ID": messageId } }, { source: true })

And I get this: 

{"level":40,"time":1666104491184,"pid":10672,"hostname":"sh-scus-dev29","component":"imap-connection","cid":"12cafco7mgtt75o72bnw","err":{"type":"Error","message":"Command failed","stack":"Error: Command failed\n    at ImapFlow.reader (C:\\Projects\\cypress-core\\node_modules\\imapflow\\lib\\imap-flow.js:521:35)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","response":{"tag":"9","command":"BAD","attributes":[{"type":"TEXT","value":"Invalid sequence set for FETCH"}]},"responseStatus":"BAD","responseText":"Invalid sequence set for FETCH"},"cid":"12cafco7mgtt75o72bnw","msg":"Command failed"}

**Additional context**
This is for a Cypress test using imapflow, nodemailer and Ethereal

Thanks!

**Comment by andris9** [comment]
`fetchOne` allows to query based on sequence numbers or UID, but not with search query
