### ISSUE TITLE
Is there a know way to connect to smtp4dev using Imapflow?

### ISSUE THREAD

**Issue by jprealini** [postalsys/imapflow#92]
I successfully implemented Imapflow in Cypress to connect and fetch Ethereal.email messages. But due to security concerns, now I've been requested to use smtp4dev instead of Ethereal. I'm wondering if there is a known way to use Imapflow with smtp4dev in the same way as I did with Ethereal

Thanks!

**Comment by andris9** [comment]
ImapFlow connects to IMAP servers but smtp4dev does not support IMAP. So you need to find another solution than ImapFlow to get these emails.
