### ISSUE TITLE
Object.keys is return string[]

### ISSUE THREAD

**Issue by AllenCoder** [postalsys/imapflow#94]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/8213915/201912126-24a1e2e4-f857-4227-859d-03d52eaf884c.png">

**Comment by andris9** [comment]
Fixed it https://github.com/postalsys/imapflow/commit/a0591c1002e9c1f42712bd9d1cb88ed9e25d6d30#diff-f2e460350636af073cbec9da5d27498feec5defb8b7b900603a10d2e017a6e5f
