### ISSUE TITLE
imap.list does not behave properly when options are passed

### ISSUE THREAD

**Issue by loup-fox** [postalsys/imapflow#95]
**Describe the bug**
Types on DefinitelyTypes are outdated and I have no idea how to use the types generated by the jsdoc.

For example I can't write this with the current version of DefinitelyType
```
imap.list({
  statusQuery: {
     nextUid: true
  }
})
```

**Comment by loup-fox** [comment]
> **Describe the bug** Types on DefinitelyTypes are outdated and I have no idea how to use the types generated by the jsdoc.
> 
> For example I can't write this with the current version of DefinitelyType
> 
> ```
> imap.list({
>   statusQuery: {
>      specialUse: true,
>      nextUid: true
>   }
> })
> ```

Plus when I use `nextUid` I lose `specialUse`

**Comment by andris9** [comment]
Can't help with types, really 🤷‍♂️ At first, I generated typings from the jsdoc comments, but these caused more issues than it helped, so I disabled these – the typings file is still built for releases, but package.json does not include a reference to the file anymore. Whatever goes on in DefinitelyTypes, I have no control over, as I don't manage these typings.
