### ISSUE TITLE
A fetchOne call to mailbox is returning false every single time

### ISSUE THREAD

**Issue by floifymatias** [postalsys/imapflow#97]
Hello, not sure where to ask this so posting an issue here. 

I have imapFlow integrated in a cypress project with ethereal, for email testing. 
I have a single implementation of getLastEmail() and it should be getting this:

I have two test cases with an identical step implementation:

```
recurse(
        () => cy.task('getLastEmail'), // Cypress commands to retry
        Cypress._.isObject, // keep retrying until the task returns an object
        {
            timeout: 60000, // retry up to 1 minute
            delay: 5000, // wait 5 seconds between attempts
        },
    )
        .its('html')
        .then((html) => {
            cy.document({ log: false }).invoke({ log: false }, 'write', html)
        })
``` 

But for some reason, one of them returns false in this task. 

                message = await client.fetchOne("*", { source: true });
                console.log(message)

The test that works shows:
```
----------------------
----------------------
----------------------
{
  seq: 1,
  source: <Buffer 44 65 6c 69 76 65 72 65 64 2d 74 6f 3a 20 79 33 7a 77 68 33 72 74 65 6c 33 69 73 75 79 73 2b 6d 61 6e 61 67 65 72 31 40 65 74 68 65 72 65 61 6c 2e 65 ... 3756 more bytes>,
  modseq: 1n,
  uid: 1,
  id: '3ac0116c2a27ddfa1f93de40f82338ff'
}
----------------------
----------------------
----------------------
```

While test that fails only shows

```
----------------------
----------------------
----------------------
false
----------------------
----------------------
----------------------
```

This is clearly some weird behavior triggered by my tests but it is exactly the same implementation for both. In which case fetchOne could be returning "false" if I'm already querying for {source: true}

Thank you!

**Comment by andris9** [comment]
`false` is returned when currently selected mailbox does not have any emails
